name: builder

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: create cache directory
        run: mkdir cache

      - name: using cache
        uses: actions@cache@v3
        with:
          key: ccache
          path: ./cache

      - name: build Docker image
        run: docker build . --file Dockerfile --tag ${{ github.repository }}:latest

      - name: run Docker image
        run: docker run -i -e GITHUB_KEY=${{ secrets.GITHUB_TOKEN }} -e REPO=${{ github.repository }} -v "$(realpath ./cache)":/home/builder/.cache/ccache  ${{ github.repository }}:latest
